# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160920_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinformations',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
