# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160622_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='location',
        ),
        migrations.AlterField(
            model_name='userfoodpreference',
            name='score',
            field=models.IntegerField(),
        ),
    ]
