# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160920_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecommendations',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.IntegerField()),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.FoodInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='foodrecommendations',
            unique_together=set([('userID', 'foodID')]),
        ),
    ]
